// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.Web.Data;

#nullable disable

namespace TimeTracker.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312134658_AddWeeklyNotesSubfolder")]
    partial class AddWeeklyNotesSubfolder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeTracker.Web.Data.Models.JournalCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JournalCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#0d6efd",
                            Icon = "bi-briefcase",
                            IsSystem = true,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#6f42c1",
                            Icon = "bi-person",
                            IsSystem = true,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#198754",
                            Icon = "bi-book",
                            IsSystem = true,
                            Name = "Learning"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#dc3545",
                            Icon = "bi-heart",
                            IsSystem = true,
                            Name = "Health"
                        });
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("JournalCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JournalTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedTimeEntryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JournalCategoryId");

                    b.HasIndex("JournalTypeId");

                    b.HasIndex("LinkedTimeEntryId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.JournalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JournalTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#ffc107",
                            Icon = "bi-lightning-charge",
                            IsSystem = true,
                            Name = "Challenge"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#0dcaf0",
                            Icon = "bi-mortarboard",
                            IsSystem = true,
                            Name = "Learning"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#198754",
                            Icon = "bi-trophy",
                            IsSystem = true,
                            Name = "Success"
                        });
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RemindOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Repeat")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliverableTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkCategoryId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AiTimeSavedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("AiUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductivityRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkCategoryId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.TimeEntryTag", b =>
                {
                    b.Property<int>("TimeEntryId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("TimeEntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TimeEntryTags");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DailyNotesSubfolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaultRootPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeeklyNotesSubfolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyNotesSubfolder = "Journal\\Daily",
                            WeeklyNotesSubfolder = "Journal\\Weekly"
                        });
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.WorkCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#0d6efd",
                            Icon = "bi-code-slash",
                            IsSystem = true,
                            Name = "Development"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#6f42c1",
                            Icon = "bi-people",
                            IsSystem = true,
                            Name = "Team Leadership"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#0dcaf0",
                            Icon = "bi-kanban",
                            IsSystem = true,
                            Name = "Board & Planning"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#ffc107",
                            Icon = "bi-calendar-event",
                            IsSystem = true,
                            Name = "Business Meetings"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#fd7e14",
                            Icon = "bi-bar-chart",
                            IsSystem = true,
                            Name = "Leadership Reporting"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#20c997",
                            Icon = "bi-diagram-3",
                            IsSystem = true,
                            Name = "Cross-Team / External"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#6c757d",
                            Icon = "bi-inbox",
                            IsSystem = true,
                            Name = "Admin / Other"
                        });
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.JournalEntry", b =>
                {
                    b.HasOne("TimeTracker.Web.Data.Models.JournalCategory", "JournalCategory")
                        .WithMany()
                        .HasForeignKey("JournalCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimeTracker.Web.Data.Models.JournalType", "JournalType")
                        .WithMany()
                        .HasForeignKey("JournalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimeTracker.Web.Data.Models.TimeEntry", "LinkedTimeEntry")
                        .WithMany()
                        .HasForeignKey("LinkedTimeEntryId");

                    b.Navigation("JournalCategory");

                    b.Navigation("JournalType");

                    b.Navigation("LinkedTimeEntry");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.TaskItem", b =>
                {
                    b.HasOne("TimeTracker.Web.Data.Models.WorkCategory", "WorkCategory")
                        .WithMany()
                        .HasForeignKey("WorkCategoryId");

                    b.Navigation("WorkCategory");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.TimeEntry", b =>
                {
                    b.HasOne("TimeTracker.Web.Data.Models.WorkCategory", "WorkCategory")
                        .WithMany("TimeEntries")
                        .HasForeignKey("WorkCategoryId");

                    b.Navigation("WorkCategory");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.TimeEntryTag", b =>
                {
                    b.HasOne("TimeTracker.Web.Data.Models.Tag", "Tag")
                        .WithMany("TimeEntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTracker.Web.Data.Models.TimeEntry", "TimeEntry")
                        .WithMany("TimeEntryTags")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.Tag", b =>
                {
                    b.Navigation("TimeEntryTags");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.TimeEntry", b =>
                {
                    b.Navigation("TimeEntryTags");
                });

            modelBuilder.Entity("TimeTracker.Web.Data.Models.WorkCategory", b =>
                {
                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
